update 5-api-reviews
Freeman-YFH/BE-NC-Games pull request #4
Opened 2023-03-28 14:42 UTC by Freeman-YFH

2023-03-28 15:01 UTC, popatre requested changes
Just needs a small refactor to make sure we're not sending back the review_body

Rest looks great

2023-03-28 15:01 UTC, popatre commented on __tests__/app.test.js
> +                        review_body: expect.any(String),
Just looking at the ticket - it doesnt want the review_body

2023-03-28 15:01 UTC, popatre commented on __tests__/app.test.js
> +                const { result } = body;
needs a key of `reviews` instead of result, please

2023-03-28 15:01 UTC, popatre commented on controllers/games.controller.js
> +            res.status(200).send({ result })
Nice one - just need the data sent back on a key of `reviews`

2023-03-28 15:01 UTC, popatre commented on models/games.model.js
> +        .query(`SELECT reviews.*, COUNT(comment_id) AS comment_count FROM reviews LEFT JOIN comments on comments.review_id = reviews.review_id GROUP BY reviews.review_id ORDER BY comment_count DESC;`
Just needs a small refactor to make sure we're not sending back the review_body

Rest looks great

2023-03-29 08:25 UTC, itskatherine reviewed
Hi Freeman, nice refactor but just remember to avoid including code that isn't aimed at this ticket on this branch 🌴 
Have a look at my comments and then once you've addressed them it's ready to merge 👍

2023-03-29 08:25 UTC, itskatherine commented on models/games.model.js
> +        .then((data) => {
Nice refactor to avoid sending the body

2023-03-29 08:25 UTC, itskatherine commented on __tests__/func.test.js
> +const { createRefObj } = require("../func/func");
I don't think this code belongs on this branch/PR - should be removed and put on the correct branch

2023-03-29 08:25 UTC, itskatherine commented on __tests__/app.test.js
> +                expect(review).toBeSortedBy("created_at", { descending: true })
Nice use of jest-sorted

2023-03-29 08:25 UTC, itskatherine commented on func/func.js
> +exports.createRefObj = (arr, key1, key2) => {
This code doesn't look like its anything to do with ticket 5 so should be on a different branch

2023-03-29 08:36 UTC, merged